name: Retrain Model

on:
  push:
    branches:
      - develop

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training script
      run: python train.py

    - name: Upload model
      uses: actions/upload-artifact@v4
      with:
        name: modelo
        path: app/modelo.pkl
    - name: Copy model to Azure VM
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USERNAME }}
        key: ${{ secrets.AZURE_PRIVATE_KEY }}
        source: "model/model.pkl"
        target: "/Users/isaaccastillo/Documents/Tarea_4/app"

    - name: Restart Streamlit (optional)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USERNAME }}
        key: ${{ secrets.AZURE_PRIVATE_KEY }}
        script: |
          pkill -f streamlit
          nohup streamlit run app/main.py &> log.txt &